### ISSUE TITLE
Build #9112 breaks vamp_stuff from working

### ISSUE THREAD

**Issue by zakhad** [Axema/Vampiric-Stuff#15]
I assume it's related to https://github.com/CleverRaven/Cataclysm-DDA/pull/31180

"Mandate description of terrain and furniture"

 DEBUG    : Error: data/mods//vamp_stuff/Modification Files/Locations/-Essentials/v_terrain.json: line 3:22: missing mandatory member "description"

[{
  "type": "terrain",
  "id": "t_blood_sh",
                     ^
  "name": "shallow blood",
10  "symbol": "~",
10  "color": "light_red",
10
 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 977

**Comment by ifreund** [comment]
Thanks for your bug report.

We don't support third party mods, please contact the mod author to report the bug.

It is unfortunate that we had to break compatibility with mods missing terrain/furniture descriptions, but it benefits the development of the game and updating the mods to accommodate this change isn't too difficult.

**Comment by Axema** [comment]
Oh, the terrain needs a description. Sorry for the late reply, I'll try to fix this problem in a jiffy ;)

**Comment by Axema** [comment]
Thanks to daniel, the error's fixed now :)

**Comment by Axema** [comment]
Thanks to daniel, the error's fixed now :)
