### ISSUE TITLE
Overmap Special occurrences: Too many minimum 1 occurrence?

### ISSUE THREAD

**Issue by Malkeus** [Axema/Vampiric-Stuff#19]
This mod has 14 overmap specials with minimum occurrences greater than 0. 
Are ALL of these absolutely required to spawn on every overmap tile for this mod to function correctly? 

My understanding is you only NEED minimum occurrences greater than 0 for a quest related location to prevent errors. I currently go through and set all the minimums to 0 or I get the 'Too many overmap specials' error with my current setup.

**Comment by Axema** [comment]
Sorry for inconvenience, I have a problem about that.

Well, since I did those on the fly, I did not use the [UNIQUE] flags to structures (it's the reason behind the error). But later I'll do a fix ;)

**Comment by Malkeus** [comment]
Much obliged :)

**Comment by Axema** [comment]
[5f39e88](https://github.com/Axema/Vampiric-Stuff/commit/1fbcf70e3cc1d87d7b0440e69ef558ee846d18b5) - Made a quickfix ;)

**Comment by Malkeus** [comment]
Ohh, so that's how those work. TIL. Thanks :)
