### ISSUE TITLE
[10086] Bonkered this mod!

### ISSUE THREAD

**Issue by Helldrone** [Axema/Vampiric-Stuff#21]
Hello! i updated from.
![image](https://user-images.githubusercontent.com/49344129/71557685-b53eea80-2a49-11ea-82ec-06ff99754386.png)
to
![image](https://user-images.githubusercontent.com/49344129/71557704-f9ca8600-2a49-11ea-8a6d-606d9c7b8b04.png)

And i got this humbug.

![image](https://user-images.githubusercontent.com/49344129/71557708-0b139280-2a4a-11ea-94d4-160d7de66a2a.png)
Crashing my save every time.
Here's the mod list if it's of any help.
![image](https://user-images.githubusercontent.com/49344129/71561278-a6b9f880-2a74-11ea-8dc6-8d01973ec168.png)

Thanks for looking!

https://youtu.be/1Isjgc0oX0s

**Comment by Axema** [comment]
It doesn't break your save and it just brings you back to the menu, so nothing to worry about that :+1: 
Aight! it'll take a little time to make some fixes!
