### ISSUE TITLE
couldn't parse color: c_gray  

### ISSUE THREAD

**Issue by sketchslayer** [Axema/Vampiric-Stuff#22]
When attempting to launch a world with this mod I get the message:

"  DEBUG    : couldn't parse color: c_gray

 FUNCTION : color_id color_manager::name_to_id(const string&) const
 FILE     : src/color.cpp
 LINE     : 102
"

followed by similar messages for other colours then one about depreciated foreground identifiers for colours.

**Comment by Axema** [comment]
I'll do a fix later :wink:

**Comment by Axema** [comment]
Problem solved!
Update your mod for the fix :grin:
