### ISSUE TITLE
Main game update breaking the mod

### ISSUE THREAD

**Issue by la-magra** [Axema/Vampiric-Stuff#23]
Since build http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/10403/changes

```
DEBUG    : Error: data/mods//vamp_stuff/Modification Files/Monsters/Zombies/Vampire.json: line 68:9: missing mandatory member "spell_data"

                "cooldown": 28
            }
        ]
        ^
         ,
        "looks_like": "mon_zombie_succumbvampire",
        "death_drops": "succumbvampire",


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1072

```

The arcana devs solved it like this: https://github.com/chaosvolt/cdda-arcana-mod/commit/1a9a20e89b03a3fb711f196630ea2349ec437465

**Comment by Axema** [comment]
Thanks for the link to the solution, the fix will be EZ :wink:

**Comment by la-magra** [comment]
Cool, keep up the good work, 👍 .
And thank you.

**Comment by Axema** [comment]
It is [fixed](https://github.com/Axema/Vampiric-Stuff/commit/9c44bc01cc0b058158a0bf3f74f3dc4d5ed642dc) now :+1:
