### ISSUE TITLE
[10489] Load crash to menu.

### ISSUE THREAD

**Issue by Helldrone** [Axema/Vampiric-Stuff#25]
Hello! it seems the most recent updates bonkered this mod, it crashes directly to menu when attempting to load a save.

![image](https://user-images.githubusercontent.com/49344129/78463596-eed56080-76de-11ea-83ff-cdbe73beb32b.png)

Thanks for checking it and for your time!

**Comment by la-magra** [comment]
Same as #24, download new mod version from [here](https://github.com/Axema/Vampiric-Stuff/issues/26).

**Comment by Axema** [comment]
Bug fixed!
