### ISSUE TITLE
Error: Vamp Start.

### ISSUE THREAD

**Issue by MeCodeMyself** [Axema/Vampiric-Stuff#27]
When choosing the vampire wannabe scenario I get this error. 
It also says it's an invalid starting location when I attempt to play it.

 DEBUG    : invalid start locations id "lmoe"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = start_location]
 FILE     : src/generic_factory.h
 LINE     : 376

Playing the latest version of your mod and the latest experimental.

**Comment by Axema** [comment]
It is fixed now :heart:
