### ISSUE TITLE
Cannot create a new character in any build

### ISSUE THREAD

**Issue by cribsmen** [Axema/Vampiric-Stuff#29]
Hi, I've been trying to troubleshoot this for a while but I haven't been able to get any world with Vampiric Stuff installed to launch. I tried every stable build, and several of the available experimental builds between the most recent and ones from weeks ago, I have tried it with a full list of mods, just Arcana + Vamp + Vamp Arcana, and no mods except for Vamp and it always encounters the same issue:
` 
DEBUG    : Error: data/mods//vamp_stuff/Modification Files/Items/Weapons/melee_weapon.json: line 3:14: duplicate entry in json object

[{
        "//": "Bloodrune upgrade add 2 cutting and 1 bashing damage, and its ultimate techniques are learned for that weapon (if available)",
        "//":
             ^
              "A weapon based to the ravager blade from MH.",
        "id": "sword_sip",
        "type": "GENERIC",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 901
`
I didn't think including the mod list was important since it doesn't matter what mods I use, I always get this message.

**Comment by Axema** [comment]
Oh, I'll fix it right away 😉

**Comment by cribsmen** [comment]
> 
> 
> Oh, I'll fix it right away 😉

Thanks! I appreciate it

**Comment by Axema** [comment]
[Done :+1:](https://github.com/Axema/Vampiric-Stuff/commit/c86d650a0c1980eb920e1e00f8fe5ebffc6918ea)
