### ISSUE TITLE
duplicate entry in json object

### ISSUE THREAD

**Issue by Dentist2904** [Axema/Vampiric-Stuff#30]
DEBUG    : Error: data/mods//vamp_stuff+arcana/NPCs/NPC_TALK_itemprocess.json: line 3:14: duplicate entry in json object

[{
        "//": "This topic is seperated due to its VERY LONG list.",
        "//":
             ^
              "Get used to the spam of token giving. I just have to ensure you get the rewards and you'll get the money without notifying you about it.",
        "id": "VAMP_ASEEKER_questinquire_ihave_essence",
        "type": "talk_topic",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 871

**Comment by Axema** [comment]
It is [fixed[(https://github.com/Axema/Vampiric-Stuff/commit/51b3ec345f068a6fefe9a8c307b543f53a1af768) :wink:

**Comment by Axema** [comment]
It is [fixed](https://github.com/Axema/Vampiric-Stuff/commit/51b3ec345f068a6fefe9a8c307b543f53a1af768) now :wink:
