### ISSUE TITLE
Grey issue is back i think

### ISSUE THREAD

**Issue by NotHereCDDA** [Axema/Vampiric-Stuff#31]
updated files, seems to still be a thing?

 DEBUG    : couldn't parse color: c_gray

 FUNCTION : color_id color_manager::name_to_id(const string&) const
 FILE     : src/color.cpp
 LINE     : 103

i will update again to doublecheck that i didn't grab the launcher version.

Edit: yea i grabbed most recent and it's still there.

**Comment by Axema** [comment]
Also fixed from discord :+1:
