### ISSUE TITLE
Vampire stuff + arcana error message

### ISSUE THREAD

**Issue by NotHereCDDA** [Axema/Vampiric-Stuff#32]
think i narrowed it down to this mod.

 DEBUG    : sym is defined as number instead of string for overmap_terrain wob (wasteland outskirts)

 FUNCTION : void oter_type_t::load(const JsonObject&, const string&)
 FILE     : src/overmap.cpp
 LINE     : 585

**Comment by Axema** [comment]
You've got an outdated mod. Update it for the fix :wink:

**Comment by NotHereCDDA** [comment]
i have updated every mod i have. it's still throwing the error? i even tried only running arcana and vamp stuff and vamp = arcana stuff mods.

**Comment by Axema** [comment]
I forgot to close this... This was solved on discord :)
