### ISSUE TITLE
Vampiric Stuff + Arcana translition.

### ISSUE THREAD

**Issue by Adevald** [Axema/Vampiric-Stuff#5]
Woah, thats unexpectedly. Is this a some kind of patch? Or total fusion of 2 mods? Im also will try to translate Arcana Mod in parallel. But now dont know the dependencies of mods.

**Comment by Adevald** [comment]
I think you should sign new folder like VampStuff (Patch - Arcana) or something. For structuring in case.

**Comment by Axema** [comment]
It isn't a patch, it's a new seperate mod to combine Arcana with mine :slightly_smiling_face:

**Comment by Adevald** [comment]
So it something like Mod for content connection of 2 mods? Maybe its not technically patch, but i think at least you need to descript it onto the README.md . Someone might be confused. Maybe...

**Comment by Adevald** [comment]
And i also have some question. How often you change names and descriptions in mods?

**Comment by Axema** [comment]
Yes. I'll notify others about the differences in these mods...

I don't know, actually... Sometimes there are temporary descriptions about items, just like drafting a note :smile:

**Comment by Adevald** [comment]
Thanks for informanion. Anyway, its my job and pain. But i'll be greatful if you dont close that issue, and sometimes help me. And another question, how bad is my English??

**Comment by Axema** [comment]
I guess 7/10 :rofl:

**Comment by Adevald** [comment]
i think its not bad how i think.

**Comment by Adevald** [comment]
@Axema,  im little bit confused... What the "hammeriuses" is?

**Comment by Axema** [comment]
Oh. About that, I have to name the weapon a wee-bit more unique. "Blood hammer" doesn't seem to fit,, so I named it "hammerius" instead.

Well, hammerius looks much like this:

![Reference](https://i.pinimg.com/originals/96/f7/da/96f7da6158b82a6585551a52f11dad59.jpg)

**Comment by Adevald** [comment]
@Axema The Hammer OF The Blood!

**Comment by Axema** [comment]
Sounds good, tho :smile:
